import Footer from 'common/footer';
import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import { MainStyled } from '../styles/styled';

interface BaseProps {
  children: React.ReactNode;
  headTitle: string;
  headElements?: React.ReactNode;
}

const Base: NextPage<BaseProps> = ({ headTitle, children, headElements }: BaseProps) => {
  return (
    <>
      <Head>
        <title>{headTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/fav/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/fav/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/fav/favicon-16x16.png" />
        <link rel="manifest" href="/fav/site.webmanifest" />
        <link rel="mask-icon" href="/fav/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />
        {headElements}
      </Head>
      <MainStyled>
        {children}
      </MainStyled>
      <Footer />
    </>
  );
};

export default Base;
