import { Container, Typography } from '@mui/material';
import Footer from 'common/footer';
import type { NextPage } from 'next';
import Head from 'next/head';
import { MainStyled } from '../styles/styled';

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Hermes Corporate Solutions | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/fav/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/fav/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/fav/favicon-16x16.png" />
        <link rel="manifest" href="/fav/site.webmanifest" />
        <link rel="mask-icon" href="/fav/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />
      </Head>

      <MainStyled>
        <h1 >
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p >
          Get started by editing{' '}
          <code >pages/index.tsx</code>
        </p>

        <div >
          <a href="https://nextjs.org/docs" >
            <Typography variant="h2">Documentation &rarr;</Typography>
            <Typography variant="body2">Find in-depth information about Next.js features and API.</Typography>
          </a>

          <a href="https://nextjs.org/learn" >
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"

          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"

          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </MainStyled>
      <Footer />
    </Container>
  );
};

export default Home;
